### ISSUE TITLE
[2.1.2-GTNH] Can't view TiC alloy recipe

### ISSUE THREAD

**Issue by ORANG4** [GTNewHorizons/NotEnoughItems#102]
Can't view some TiC alloy recipes by clicking on liquid from casting table recipe screen and NEI itself.
**Modpack:** FTB Infinity Evolved 3.1.0

idk, is it the same issue or not, but I also can't view Thermal Expansion's Magma Crucible liquids recipes from any screen but Magma Crucible itself. [Log error](https://pastebin.com/Wwb98c3d). Btw, usages are showing after 3-5 clicks with same log error.

update: same log errors when I'm viewing different recipes form different mods. i.e. it requiers 3-5 clicks for recipe to show.

![image](https://user-images.githubusercontent.com/59235403/115018134-2bc25e80-9ec0-11eb-9a52-a6823e942548.png)
![image](https://user-images.githubusercontent.com/59235403/115023397-68de1f00-9ec7-11eb-9b4f-125ee4c8c346.png)

**Comment by mitchej123** [comment]
This is fixed in 2.1.1.  Grab it off curse forge.

**Comment by Dream-Master** [comment]
Or use this
http://jenkins.usrv.eu:8080/job/Tinkers-Construct/8/

**Comment by ORANG4** [comment]
> This is fixed in 2.1.1. Grab it off curse forge.

Sorry, my fault.

But I still can't open TiC alloy recipe from casting table recipe screen (by clicking on flowing liquid)
![image](https://user-images.githubusercontent.com/59235403/115089424-e1220000-9f1a-11eb-8f17-aa4c7c329a58.png)

**Comment by mitchej123** [comment]
I tried that on the original NEI, and I don't think it worked there either...

**Comment by mitchej123** [comment]
If I'm wrong, and you can find a version for 1.7.10 it worked on, please let me know so I can see what changed between the two versions.

**Comment by Prometheus0000** [comment]
It might be a TC bug, because it works with the CF TC and beta 18. And I remember it working in our pack before too.

**Comment by Prometheus0000** [comment]
...it stopped working once I maximized the window. Though it still shows the tooltip, so it's probably NEI after all.

**Comment by Prometheus0000** [comment]
In beta5 it's in the wrong place when maximized, but if you find it you can click through.
It works in beta9, but not 11, and there is no 10.

**Comment by ORANG4** [comment]
> If I'm wrong, and you can find a version for 1.7.10 it worked on, please let me know so I can see what changed between the two versions.

It's working as intended in 1.7.10-1.0.5.120

In 2.1.2-GTNH it looks like the bug occurs when with window height is not 1080px

https://user-images.githubusercontent.com/59235403/115112921-57147e80-9f90-11eb-83bb-5d6888dab6b1.mp4

**Comment by mitchej123** [comment]
That must be why it didn't work, I tried it with the 1.x series and had no luck, but I wasn't running at 1080p.

I'll try to fix it in NEI, but It's really a TC bug, they do weird things to determine the correct y position.

**Comment by KaneHart** [comment]
I tried in 1080P without it working. That being said I use a third party program to force borderless as fullscreen is meh in MC... 

Not the worst thing ever if it does not work, but I do miss it. Hit me quite fast early on.

**Comment by Prometheus0000** [comment]
Try moving the mouse cursor up or down on the screen to find it.
